### ISSUE TITLE
Method `checkPermission` always gives false

### ISSUE THREAD

**Issue by zi9o** [pardjs/nest-casbin#2]
Hi @bgdsh, 
Firstly I want to thank you for this PR, and its simple integration. Although I keep getting `false` when using `checkPermission` method for every added policy, Would you please provide a simple example on how to add/check permissions?
Thanks in advance ;)

**Comment by GinaMaronov** [comment]
add the following to rbac_policy.csv:

p, alice, /, GET

Note: that username (req.user) is hardcoded in authz.ts. You can change the code to read it from body. Reading from query string will take a little more work since it messes up the path but not too bad.

**Comment by hsluoyz** [comment]
@zi9o

**Comment by zi9o** [comment]
> @zi9o 

Thanks for mentioning me

**Comment by hsluoyz** [comment]
@zi9o feel free to close it if resolved :)
